version: '2'

services:
  mongo: 
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
    user: "${UID_GID}"
    ports:
      - "27017:27017"
    networks:
      - common
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    user: "${UID_GID}"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    networks: 
      - common
    restart: always

networks: 
  common: